######################################################################
# Automatically generated by qmake (3.1) Mon Apr 17 11:24:07 2017
######################################################################

TEMPLATE = app
TARGET = Savanna_Simulator
INCLUDEPATH += .

# Input
HEADERS += animal.hpp console.hpp mainwindow.hpp simulation.hpp
SOURCES += animal.cpp console.cpp mainwindow.cpp QtMain.cpp simulation.cpp

QT += widgets
